#pragma once

enum class FTP_DATA_MODE
{
    NONE,
    PASV,
    PORT
};

enum class FTP_AUTH_STATUS
{
    AWAIT_USER,
    AWAIT_PASS,
    AUTHORIZED
};

enum class FTP_RETURN_CODE
{
    DATA_SOCK_ALREADY_OPEN = 125,
    OPENING_DATA_SOCK = 150,

    SUCCESS = 200,
    COMMAND_NOT_IMPLEMENTED = 202,
    DIRECTORY_STATUS = 212,
    FILE_STATUS = 213,
    NAME = 215,
    READY_FOR_NEW_USER = 220,
    GOODBYE = 221,
    CLOSING_DATA = 226,
    ENTER_PASV_MODE = 227,
    LOGIN_SUCCESSFUL = 230,
    FILE_ACTION_OK = 250,
    PATHNAME_CREATED = 257,

    USER_NEED_PASS = 331,
    USER_NEED_ACCOUNT = 332,
    FILE_ACTION_NEED_INFO = 350,

    SHUTTING_DOWN = 421,
    CANT_OPEN_DATA = 425,
    INVALID_PASS_NAME = 430,
    FILE_UNAVAILABLE = 452,
    
    UNKNOWN_COMMAND = 502,
    SYNTAX_ERROR = 501,
    BAD_SEQUENCE = 503,
    NOT_LOGGED_IN = 530,
    FAILED_FILE_OP = 550,
    FAILED_FILE_SAVE = 552
};
